name: nanumi
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
    
  cupertino_icons: ^1.0.2
  flutter_riverpod: ^2.1.3
  firebase_core: ^2.4.1
  json_serializable: ^6.6.1
  cloud_firestore: ^4.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.3.3

flutter:
  uses-material-design: true

  assets:
    - assets/